In [31]:
pip install joblib


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [32]:
import joblib
import torch
import numpy as np

In [3]:
filename="txt_pOWe4zB-E-4.joblib"
txt=joblib.load(filename, mmap_mode=None)
print(txt.shape)

(9, 512)


In [4]:
vid_filename="vid_pOWe4zB-E-4.joblib"
vid=joblib.load(vid_filename, mmap_mode=None)
print(vid.shape)

(500, 512)


In [5]:
filename="txt_pq2PcaRnzc4.joblib"
txt2=joblib.load(filename, mmap_mode=None)
print(txt2.shape)

(14, 512)


In [15]:
vid_filename="vid_pq2PcaRnzc4.joblib"
vid2=joblib.load(vid_filename, mmap_mode=None)
vid2=torch.tensor(vid2)
print(vid2.shape)

torch.Size([500, 512])


In [49]:
from evaluate import compute_all_metrics

In [31]:
pip install lmdb

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [24]:
import pandas as pd
d={'num_steps':[9,14],'frame_features':[vid,vid2],'step_features':[txt,txt2]}
dataset=pd.DataFrame(d)
for sample in dataset:
    print(sample)
    print(sample['num_steps'])
    print(sample['frame_features'].shape)
    print(sample['step_features'].shape)

num_steps


TypeError: string indices must be integers

In [44]:
from evaluate import framewise_eval,compute_all_metrics

In [51]:
class Config:
    def __init__(self, dataset,name,distance,dp_algo,drop_cost,keep_percentile,use_unlabeled):
        self.dataset = dataset
        self.name = name
        self.distance = distance
        self.dp_algo = dp_algo
        self.drop_cost = drop_cost
        self.keep_percentile = keep_percentile
        self.use_unlabeled=use_unlabeled
        

In [52]:
config=Config('YouCook2','','cos','DropDTW','logit',0.3,True)

In [47]:
config.distance

'cos'

In [62]:
model=None
gamma=1
compute_all_metrics(dataset,model,gamma,config)

100%|██████████| 1192/1192 [00:34<00:00, 34.68it/s]


(38.847147651006644,
 9.65700773103205,
 44.0263422818792,
 12.285798828504483,
 0.2713851498046027)

In [ ]:
return accuracy_std * 100, iou_std * 100, accuracy_dtw * 100, iou_dtw * 100, recall

In [67]:
config.drop_cost1

AttributeError: 'dict' object has no attribute 'drop_cost1'

In [32]:
name: name of the example
cls: class (or activity) of the video
cls_name: name of the class (or activity)
num_frames: Number of frames N
frame_features: features from all N frames in the video, has size [N, d]
num_steps: Number of steps K
step_ids: ids of steps that happen in this video, has len K
step_features: Feature matrix of size [K, d], where d
step_starts: start of each step (in frames)
step_ends: end of each step (in frames)

SyntaxError: invalid syntax (<ipython-input-32-3dab9a9635ca>, line 1)

In [23]:
import json
 
# Opening JSON file
f = open('youcookii_annotations_trainval.json')
 
# returns JSON object as
# a dictionary
data = json.load(f)
data=data['database']

In [39]:
def getData(id,data,mypath):
    final_dict={}
    step_ids=[]
    step_starts_sec=[]
    step_ends_sec=[]
    duration=data['duration']
    txt_filename=mypath+'text/txt_'+str(id)+'.joblib'
    video_filename=mypath+'video/vid_'+str(id)+'.joblib'
    text_features=joblib.load(txt_filename, mmap_mode=None)
    text_features=torch.tensor(text_features)
    video_features=joblib.load(video_filename, mmap_mode=None)
    video_features=torch.tensor(video_features)
    
    frames=len(video_features)
    
    final_dict['name']=id
    final_dict['cls']=data['recipe_type']
    final_dict['cls_name']=data['recipe_type']
    final_dict['num_frames']=torch.tensor(frames)
    final_dict['frame_features']=video_features
    final_dict['num_steps']=torch.tensor(len(text_features))
    final_dict['step_features']=text_features
    
    for val in data['annotations']:
        step_ids.append(val['id'])
        step_starts_sec.append(val['segment'][0])
        step_ends_sec.append(val['segment'][1])
        
    final_dict['step_ids']=torch.tensor(step_ids)
    final_dict['step_starts_sec']=torch.tensor(step_starts_sec)
    final_dict['step_ends_sec']=torch.tensor(step_ends_sec)
    final_dict['step_ends'] = np.array(
    [int((s*frames)//duration) for s in step_ends_sec]
    )
    final_dict['step_starts'] = np.array(
    [int((s*frames)//duration) for s in step_starts_sec]
    )
    
    return final_dict


In [40]:
dataset=[]
path='./CLIP_FEAT/training/'
dataset.append(getData('pOWe4zB-E-4',data['pOWe4zB-E-4'],path))
# dataset.append(getData('pq2PcaRnzc4',data['pq2PcaRnzc4']))

In [35]:
dataset

[{'name': 'pOWe4zB-E-4',
  'cls': '425',
  'cls_name': '425',
  'num_frames': tensor(500),
  'frame_features': tensor([[-0.1498, -0.2634, -0.5659,  ...,  0.7729, -0.3650, -0.2932],
          [-0.2961, -0.0937,  0.2305,  ...,  1.1836,  0.0320, -0.0127],
          [-0.8257, -0.3501,  0.0958,  ...,  1.0938, -0.2103,  0.1567],
          ...,
          [-0.4021, -0.0199, -0.1875,  ...,  1.2236, -0.1443,  0.3391],
          [-0.4875,  0.0098, -0.2311,  ...,  1.1357, -0.1349,  0.3179],
          [-0.1498, -0.2634, -0.5659,  ...,  0.7729, -0.3650, -0.2932]]),
  'num_steps': tensor(9),
  'step_features': tensor([[-0.1165,  0.0089,  0.0501,  ...,  0.8604, -0.2446,  0.0275],
          [-0.2649,  0.0190,  0.0769,  ...,  0.5029, -0.0727, -0.5811],
          [-0.3186, -0.3428,  0.0249,  ...,  0.4702, -0.2244,  0.1191],
          ...,
          [-0.0118, -0.3308,  0.2417,  ...,  0.3335, -0.3528, -0.0211],
          [-0.1559, -0.0925,  0.2240,  ...,  0.6509, -0.5757, -0.1139],
          [-0.1427, -0.4

In [36]:
import tqdm

In [26]:
from os import listdir
from os.path import isfile, join
mypath='./CLIP_FEAT/training/video'
# onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
# onlyfiles

In [59]:
dataset=[]
path='./CLIP_FEAT/training/'
for f in listdir(mypath):
    id=f[4:15]
    if(id!='hJzPVZf6JVo'):
        dataset.append(getData(id,data[id],path))

In [60]:
len(dataset)

1192

In [64]:
import pickle
with open('dataset.pickle', 'wb') as f:
    pickle.dump(dataset, f)


In [67]:
import train

In [69]:
import argparse

In [ ]:
class TrainConfig:
    def __init__(self, dataset,name,distance,dp_algo,drop_cost,keep_percentile,use_unlabeled):
        self.dataset = dataset
        self.name = name
        self.distance = distance
        self.dp_algo = dp_algo
        self.drop_cost = drop_cost
        self.keep_percentile = keep_percentile
        self.use_unlabeled=use_unlabeled
        

In [66]:
# data = dataset
# model = EmbeddingsMapping(
#     d=512, learnable_drop=(args.drop_cost == 'learn'), video_layers=args.video_layers,
#     text_layers=args.text_layers, normalization_dataset=data.train_dataset,
#     batchnorm=args.batchnorm)

# # load drop costs from a pre-trained model
# if args.pretrained_drop:
#     # assumes that the model with the same name has been already trained
#     # this retraines the model, but uses drop_mapping intialization from the previous training
#     from glob import glob
#     weights_path = glob(os.path.join(WEIGHTS_PATH, args.name, f"weights-epoch=*.ckpt"))[0]
#     state_dict = {k[6:]: v for k, v in torch.load(weights_path, map_location=device)['state_dict'].items()
#                   if k.startswith('model.drop_mapping')}
#     model.load_state_dict(state_dict, strict=False)

# train_module = TrainModule(model, data)

# checkpoint_callback = pl.callbacks.ModelCheckpoint(
#     monitor='Metrics/Recall',
#     dirpath=os.path.join(PROJECT_PATH, 'weights', args.name),
#     filename='weights-{epoch:02d}',
#     save_top_k=1,
#     mode='max',
# )
# vis_callback = VisualizationCallback()
# logger = pl.loggers.TensorBoardLogger('tb_logs', args.name)

# trainer = pl.Trainer(gpus=1, callbacks=[checkpoint_callback, vis_callback],
#                      max_epochs=args.epochs, logger=logger)

# trainer.fit(train_module, data)

NameError: name 'EmbeddingsMapping' is not defined

In [1]:
import pickle as pkl

In [4]:
with open('dataset.pickle', 'rb') as f:
    data = pkl.load(f)
print(len(data))

In [9]:
print(len(data))

1192


In [69]:
#s3d feautres
def getDatas3d(id,data,mypath):
    final_dict={}
    step_ids=[]
    step_starts_sec=[]
    step_ends_sec=[]
    duration=data['duration']
    txt_filename=mypath+'/text_embeddings/'+str(id)+'.pt'
    video_filename=mypath+'s3d_features/'+str(id)+'.npy'
    text_feats=torch.load(txt_filename)
    text_features=text_feats["text_embedding"].to(dtype=float)
    video_features=np.load(video_filename)
    video_features=torch.tensor(video_features)
    
    frames=len(video_features)
    
    final_dict['name']=id
    final_dict['cls']=data['recipe_type']
    final_dict['cls_name']=data['recipe_type']
    final_dict['num_frames']=torch.tensor(frames)
    final_dict['frame_features']=video_features
    final_dict['num_steps']=torch.tensor(len(text_features))
    final_dict['step_features']=text_features
    
    for val in data['annotations']:
        step_ids.append(val['id'])
        step_starts_sec.append(val['segment'][0])
        step_ends_sec.append(val['segment'][1])
        
    final_dict['step_ids']=torch.tensor(step_ids)
    final_dict['step_starts_sec']=torch.tensor(step_starts_sec)
    final_dict['step_ends_sec']=torch.tensor(step_ends_sec)
    final_dict['step_ends'] = np.array(
    [int((s*frames)//duration) for s in step_ends_sec]
    )
    final_dict['step_starts'] = np.array(
    [int((s*frames)//duration) for s in step_starts_sec]
    )
    
    return final_dict


In [70]:
from os import listdir
from os.path import isfile, join
dataset=[]
mypath='./s3d_features/'
path='./'
i=0
for f in listdir(mypath):
    id=f[:11]
#     print(id)
      
    if id!='PqyqB_FkWrQ' and id in data:
        dataset.append(getDatas3d(id,data[id],path))

In [58]:
print(len(dataset))

1672


In [45]:
print('ZGFoNfn4tBg' in data)

False


In [33]:
import json
 
# Opening JSON file
f = open('youcookii_annotations_trainval.json')
 
# returns JSON object as
# a dictionary
data = json.load(f)
data=data['database']

In [72]:
model=None
gamma=1
compute_all_metrics(dataset,model,gamma,config)

100%|██████████| 1672/1672 [00:24<00:00, 68.37it/s] 


(53.038015380880985,
 31.71463833389377,
 62.95751898223876,
 41.87704176602314,
 11.00881943369952)

In [73]:
import pickle
with open('s3d_dataset.pickle', 'wb') as f:
    pickle.dump(dataset, f)

OSError: [Errno 122] Disk quota exceeded

In [71]:
for sample in dataset:
    print(sample['frame_features'])
    print(sample['frame_features'].type)
    print(sample['step_features'])
    print(sample['step_features'])
    print(sample['step_features'].type)
    sim = (sample['step_features'] @ sample['frame_features'].T)
    break

tensor([[-0.0050, -0.0490,  0.0059,  ...,  0.0014, -0.0144,  0.0187],
        [-0.0289, -0.0180, -0.0198,  ...,  0.0232, -0.0047,  0.0262],
        [ 0.0048, -0.0178, -0.0122,  ...,  0.0180, -0.0120,  0.0086],
        ...,
        [-0.0095,  0.0159,  0.0062,  ...,  0.0113, -0.0084,  0.0288],
        [-0.0016,  0.0165,  0.0009,  ...,  0.0036, -0.0058,  0.0216],
        [-0.0110,  0.0063, -0.0051,  ...,  0.0051, -0.0092,  0.0267]],
       dtype=torch.float64)
<built-in method type of Tensor object at 0x7f212b256c80>
tensor([[ 8.8086, 18.8481,  5.6956,  ...,  5.0874,  2.4268, -1.2983],
        [11.6736, -0.3964, -1.8675,  ..., 11.3856, 10.9289, -1.2079],
        [-0.0474, 10.2388,  4.3133,  ..., -6.5701,  0.8452,  7.0208],
        [ 1.8079,  3.9229, -6.9373,  ..., -1.0768,  1.4951,  4.4176]],
       dtype=torch.float64, grad_fn=<CopyBackwards>)
tensor([[ 8.8086, 18.8481,  5.6956,  ...,  5.0874,  2.4268, -1.2983],
        [11.6736, -0.3964, -1.8675,  ..., 11.3856, 10.9289, -1.2079],
      

In [ ]:
accuracy_std * 100, iou_std * 100, accuracy_dtw * 100, iou_dtw * 100, recall